export type CoachCategory = 'U7' | 'U9' | 'U11' | 'U13' | 'U15' | 'U18' | 'SENIORS'

export type CoachSessionTemplate = {
  id: string
  category: CoachCategory
  title: string
  objective: string
  duration: number
  level: 'découverte' | 'formation' | 'compétition' | 'performance'
  bcvbPillar: 'Défendre Fort' | 'Courir' | 'Partager la Balle' | 'Homme à Homme'
  pedagogicalStep: 'je découvre' | 'je m’exerce' | 'je retranscris en match' | 'je régule'
  description: string
  blocks: string[]
}

export const coachCategoryLabels: Record<CoachCategory, string> = {
  U7: 'U7',
  U9: 'U9',
  U11: 'U11',
  U13: 'U13',
  U15: 'U15',
  U18: 'U18',
  SENIORS: 'Seniors',
}

export const coachSessionTemplates: CoachSessionTemplate[] = [
  {
    id: 'u7-motricite-ballon',
    category: 'U7',
    title: 'Motricité + ballon',
    objective: 'Découvrir les déplacements, manipuler le ballon et rester actif.',
    duration: 60,
    level: 'découverte',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je découvre',
    description: 'Séance simple avec parcours, jeux courts et tirs proches pour garder le plaisir et le mouvement.',
    blocks: ['Accueil + consigne imagée', 'Parcours motricité ballon', 'Jeu de poursuite', 'Tirs proches', 'Mini-match guidé'],
  },
  {
    id: 'u7-decouverte-dribble',
    category: 'U7',
    title: 'Découverte du dribble',
    objective: 'Dribbler en avançant sans regarder uniquement le ballon.',
    duration: 55,
    level: 'découverte',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je découvre',
    description: 'Un cadre très visuel pour alterner exploration, relais et petits défis.',
    blocks: ['Manipulation libre', 'Relais dribble', 'Changement de direction', 'Défi cerceaux', 'Retour calme ballon'],
  },
  {
    id: 'u7-opposition-simple',
    category: 'U7',
    title: 'Jeux d’opposition simples',
    objective: 'Accepter une opposition légère et protéger son ballon.',
    duration: 60,
    level: 'découverte',
    bcvbPillar: 'Défendre Fort',
    pedagogicalStep: 'je découvre',
    description: 'Jeux courts avec règles simples pour entrer dans le duel sans surcharger les enfants.',
    blocks: ['Échauffement duel miroir', 'Protéger son ballon', 'Atteindre la zone', '1c1 très court', 'Bilan verbal'],
  },
  {
    id: 'u9-dribbler-passer-tirer',
    category: 'U9',
    title: 'Dribbler, passer, tirer',
    objective: 'Enchaîner trois fondamentaux dans une situation ludique.',
    duration: 75,
    level: 'formation',
    bcvbPillar: 'Partager la Balle',
    pedagogicalStep: 'je m’exerce',
    description: 'Séance de fondamentaux avec beaucoup de répétitions et peu d’attente.',
    blocks: ['Activation dribble', 'Passe et suit', 'Tir proche', '2c1 guidé', 'Mini-match avec bonus passe'],
  },
  {
    id: 'u9-jouer-vers-avant',
    category: 'U9',
    title: 'Jouer vers l’avant',
    objective: 'Regarder devant, courir et avancer le ballon vite.',
    duration: 75,
    level: 'formation',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je m’exerce',
    description: 'Progression simple pour apprendre à relancer et occuper les couloirs.',
    blocks: ['Courses sans ballon', 'Relance à deux', 'Passe avant dribble', '2c1 transition', 'Jeu dirigé'],
  },
  {
    id: 'u9-1c1-decouverte',
    category: 'U9',
    title: '1c1 découverte',
    objective: 'Oser attaquer le cercle et rester devant son joueur.',
    duration: 70,
    level: 'formation',
    bcvbPillar: 'Homme à Homme',
    pedagogicalStep: 'je découvre',
    description: 'Premiers duels avec espaces larges, départs variés et consignes simples.',
    blocks: ['Appuis départ', '1c0 vitesse', '1c1 couloir large', 'Défenseur miroir', 'Défi final'],
  },
  {
    id: 'u11-1c1-offensif',
    category: 'U11',
    title: '1c1 offensif',
    objective: 'Créer un avantage avec le premier appui et finir près du cercle.',
    duration: 90,
    level: 'formation',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je m’exerce',
    description: 'Séance centrée sur départs, lecture du défenseur et agressivité maîtrisée.',
    blocks: ['Appuis + départs', '1c0 finition', '1c1 couloir', '1c1 avec aide tardive', 'Jeu réduit'],
  },
  {
    id: 'u11-demarquage-simple',
    category: 'U11',
    title: 'Démarquage simple',
    objective: 'Se rendre disponible, recevoir et enchaîner vite.',
    duration: 85,
    level: 'formation',
    bcvbPillar: 'Partager la Balle',
    pedagogicalStep: 'je m’exerce',
    description: 'Développer l’appel, le timing et la passe dans des petits espaces.',
    blocks: ['Appel sans ballon', 'Passe et coupe', '2c2 démarquage', '3c3 sans dribble', 'Bilan collectif'],
  },
  {
    id: 'u11-defense-porteur',
    category: 'U11',
    title: 'Défense porteur',
    objective: 'Se placer entre le joueur et le panier, contenir et communiquer.',
    duration: 85,
    level: 'formation',
    bcvbPillar: 'Défendre Fort',
    pedagogicalStep: 'je m’exerce',
    description: 'Construire les bases de la défense Homme à Homme sur porteur.',
    blocks: ['Posture défensive', 'Miroir', '1c1 contenir', 'Stop + relance', 'Jeu dirigé défense'],
  },
  {
    id: 'u13-1c1-contact',
    category: 'U13',
    title: '1c1 avec contact',
    objective: 'Attaquer fort en gardant la maîtrise malgré le contact.',
    duration: 90,
    level: 'compétition',
    bcvbPillar: 'Défendre Fort',
    pedagogicalStep: 'je retranscris en match',
    description: 'Duel cadré pour travailler agressivité, protection du ballon et finition.',
    blocks: ['Activation contact', 'Départs opposés', '1c1 couloir serré', 'Aide tardive', '3c3 transfert'],
  },
  {
    id: 'u13-aide-defensive',
    category: 'U13',
    title: 'Aide défensive',
    objective: 'Aider côté ballon puis reprendre son joueur sans se désorganiser.',
    duration: 90,
    level: 'compétition',
    bcvbPillar: 'Homme à Homme',
    pedagogicalStep: 'je m’exerce',
    description: 'Bases de l’aide-reprise en Homme à Homme avec communication obligatoire.',
    blocks: ['Postures aide', '2c2 aide', '3c3 côté ballon', 'Stop + relance', 'Régulation coach'],
  },
  {
    id: 'u13-jeu-rapide',
    category: 'U13',
    title: 'Jeu rapide',
    objective: 'Courir après stop défensif et décider vite sans précipitation.',
    duration: 90,
    level: 'compétition',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je retranscris en match',
    description: 'Relance, couloirs, finition rapide et lecture du surnombre.',
    blocks: ['Relance à 3', '2c1 transition', '3c2 continu', 'Stop + courir', 'Jeu avec bonus transition'],
  },
  {
    id: 'u15-defense-homme-homme',
    category: 'U15',
    title: 'Défense Homme à Homme',
    objective: 'Tenir son duel, communiquer et protéger l’axe.',
    duration: 100,
    level: 'compétition',
    bcvbPillar: 'Homme à Homme',
    pedagogicalStep: 'je retranscris en match',
    description: 'Séance structurée pour installer règles défensives et responsabilités individuelles.',
    blocks: ['Close-out', '1c1 pression', '2c2 aide-reprise', '4c4 règles H-H', 'Bilan vidéo ou tableau'],
  },
  {
    id: 'u15-transition-offensive',
    category: 'U15',
    title: 'Transition offensive',
    objective: 'Relancer vite, occuper les couloirs et finir avec maîtrise.',
    duration: 100,
    level: 'compétition',
    bcvbPillar: 'Courir',
    pedagogicalStep: 'je retranscris en match',
    description: 'Passer du stop défensif à l’avantage offensif en quelques secondes.',
    blocks: ['Sortie de balle', '3 couloirs', '3c2 continu', '5c0 rythme', '5c5 contrainte stop + courir'],
  },
  {
    id: 'u15-agressivite-cercle',
    category: 'U15',
    title: 'Agressivité vers le cercle',
    objective: 'Attaquer l’espace libre, provoquer l’aide et ressortir si besoin.',
    duration: 95,
    level: 'compétition',
    bcvbPillar: 'Partager la Balle',
    pedagogicalStep: 'je retranscris en match',
    description: 'Développer fixation, finition, passe de sortie et prise de décision.',
    blocks: ['1c1 avantage', 'Drive + kick', '2c2 aide', '3c3 avantage', 'Jeu dirigé'],
  },
  {
    id: 'u18-intensite-defensive',
    category: 'U18',
    title: 'Intensité défensive',
    objective: 'Maintenir une pression élevée sans perdre la maîtrise.',
    duration: 105,
    level: 'performance',
    bcvbPillar: 'Défendre Fort',
    pedagogicalStep: 'je régule',
    description: 'Séance exigeante avec rotations, communication et standards défensifs.',
    blocks: ['Activation compétitive', '1c1 pression', 'Shell drill', '5c5 stops obligatoires', 'Débrief standards'],
  },
  {
    id: 'u18-lecture-responsabilites',
    category: 'U18',
    title: 'Lecture et responsabilités',
    objective: 'Lire l’avantage, décider vite et assumer son rôle collectif.',
    duration: 105,
    level: 'performance',
    bcvbPillar: 'Partager la Balle',
    pedagogicalStep: 'je régule',
    description: 'Situations à contraintes pour faire émerger les décisions des joueurs.',
    blocks: ['Lecture 2c1', '3c3 avantage', '4c4 contraintes', '5c5 rôles', 'Auto-évaluation'],
  },
  {
    id: 'u18-preparation-match',
    category: 'U18',
    title: 'Préparation match',
    objective: 'Préparer le plan de jeu, les situations spéciales et l’intensité attendue.',
    duration: 105,
    level: 'performance',
    bcvbPillar: 'Homme à Homme',
    pedagogicalStep: 'je retranscris en match',
    description: 'Répétition structurée des priorités du week-end et situations de fin de match.',
    blocks: ['Activation ciblée', 'Plan défensif', 'Jeu rapide', 'Situations spéciales', 'Fin de match'],
  },
  {
    id: 'seniors-preparation-match',
    category: 'SENIORS',
    title: 'Préparation match',
    objective: 'Aligner plan de match, intensité et rôles avant compétition.',
    duration: 110,
    level: 'performance',
    bcvbPillar: 'Homme à Homme',
    pedagogicalStep: 'je retranscris en match',
    description: 'Séance dense pour préparer les priorités adverses et les réponses collectives.',
    blocks: ['Activation spécifique', 'Plan défensif', 'Options offensives', 'Special situations', 'Clôture rôle par rôle'],
  },
  {
    id: 'seniors-intensite-defensive',
    category: 'SENIORS',
    title: 'Intensité défensive',
    objective: 'Installer un niveau de pression cohérent sur toute la séance.',
    duration: 105,
    level: 'performance',
    bcvbPillar: 'Défendre Fort',
    pedagogicalStep: 'je régule',
    description: 'Travail des standards défensifs, du rebond et de la relance après stop.',
    blocks: ['Standards défense', '1c1 / 2c2 pression', 'Shell + rotations', '5c5 stops', 'Bilan charge'],
  },
  {
    id: 'seniors-situations-specifiques',
    category: 'SENIORS',
    title: 'Situations spécifiques',
    objective: 'Répéter les remises en jeu, fins de possession et fins de match.',
    duration: 95,
    level: 'performance',
    bcvbPillar: 'Partager la Balle',
    pedagogicalStep: 'je régule',
    description: 'Séance orientée précision, responsabilités et exécution sous pression.',
    blocks: ['BLOB/SLOB', 'Fin de possession', 'Stop ou faute', 'Score serré', 'Débrief choix'],
  },
]

export function getTemplatesByCategory(category?: CoachCategory | 'all') {
  if (!category || category === 'all') return coachSessionTemplates
  return coachSessionTemplates.filter((template) => template.category === category)
}

