import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/context/AuthContext'
import { normalizeRole } from '../../config/roles'
import { canManageOperationalPlanning, deactivateTrainingSlot, loadOperationalPlanning, saveTrainingSlot, slotsConflict, type OperationalTeam, type SlotInput, type TrainingSlot } from './operationalPlanningService'
import { getPlanningLocalDay } from './planningLocalDate'
import './operationalPlanning.css'

const weekdays = ['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']
const createEmptySlot = (): SlotInput => ({ team_id: '', season: '', weekday: 1, start_time: '', end_time: '', location_name: '', valid_from: getPlanningLocalDay().date, valid_until: null })

export default function OperationalPlanningPage() {
  const { profile } = useAuth()
  const [slots,setSlots]=useState<TrainingSlot[]>([]), [teams,setTeams]=useState<OperationalTeam[]>([])
  const [category,setCategory]=useState('all'), [teamFilter,setTeamFilter]=useState('all')
  const [form,setForm]=useState<SlotInput>(createEmptySlot), [editing,setEditing]=useState(false), [loading,setLoading]=useState(true)
  const [message,setMessage]=useState<{kind:'error'|'success';text:string}|null>(null)
  const normalizedRole=normalizeRole(profile?.role)
  const canManage=canManageOperationalPlanning(profile?.role)
  const teamBasePath=normalizedRole==='dirigeant'?'/club/equipes':normalizedRole==='parent_referent'?'/parents-referents/equipes':normalizedRole==='team_staff'?'/equipe/communication':'/equipes'
  async function reload(){const data=await loadOperationalPlanning();setSlots(data.slots);setTeams(data.teams)}
  useEffect(()=>{reload().catch(e=>setMessage({kind:'error',text:e.message})).finally(()=>setLoading(false))},[])
  const filtered=useMemo(()=>slots.filter(s=>(category==='all'||s.team?.category===category)&&(teamFilter==='all'||s.team_id===teamFilter)),[slots,category,teamFilter])
  const conflictIds=useMemo(()=>new Set(filtered.flatMap((slot,i)=>filtered.slice(i+1).filter(other=>slotsConflict(slot,other)).flatMap(other=>[slot.id,other.id]))),[filtered])
  function edit(slot:TrainingSlot){setForm({id:slot.id,team_id:slot.team_id,season:slot.season,weekday:slot.weekday,start_time:slot.start_time.slice(0,5),end_time:slot.end_time.slice(0,5),location_name:slot.location_name,valid_from:slot.valid_from,valid_until:slot.valid_until});setEditing(true);setMessage(null)}
  async function submit(event:React.FormEvent){event.preventDefault();setMessage(null);try{let result=await saveTrainingSlot(form);if(result.conflicts.length){const labels=result.conflicts.map(c=>`${c.team_name} · ${c.start_time.slice(0,5)}-${c.end_time.slice(0,5)}`).join('\n');if(!window.confirm(`Chevauchement de salle détecté :\n${labels}\n\nUtilisez cet override uniquement si le partage de la salle est volontaire. Enregistrer malgré ce chevauchement ?`))return;result=await saveTrainingSlot(form,true)}await reload();setForm(createEmptySlot());setEditing(false);setMessage({kind:'success',text:'Créneau confirmé par le serveur.'})}catch(e){setMessage({kind:'error',text:e instanceof Error?e.message:'Enregistrement impossible.'})}}
  async function disable(id:string){if(!window.confirm('Désactiver ce créneau ? Il restera conservé dans l’historique.'))return;try{await deactivateTrainingSlot(id);await reload();setMessage({kind:'success',text:'Créneau désactivé et confirmation serveur reçue.'})}catch(e){setMessage({kind:'error',text:e instanceof Error?e.message:'Désactivation impossible.'})}}
  return <main className="operational-planning bcvb-page-shell bcvb-page-shell--wide">
    <header className="operational-planning__hero"><div><p className="bcvb-eyebrow">Planning opérationnel partagé</p><h1>Créneaux des équipes</h1><p>Salles et horaires récurrents du club. La planification sportive annuelle reste disponible séparément.</p><p>Limite GO LIVE : les exceptions ponctuelles seront traitées dans le lot suivant.</p></div><Link to="/planifications">Ouvrir la planification sportive</Link></header>
    <section className="operational-planning__filters"><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Toutes</option>{[...new Set(teams.map(t=>t.category))].map(x=><option key={x}>{x}</option>)}</select></label><label>Équipe<select value={teamFilter} onChange={e=>setTeamFilter(e.target.value)}><option value="all">Toutes</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></section>
    {message&&<p role={message.kind==='error'?'alert':'status'} className={`operational-planning__message is-${message.kind}`}>{message.text}</p>}
    {canManage&&<form className="operational-planning__form" onSubmit={submit}><h2>{editing?'Modifier le créneau':'Créer un créneau'}</h2><label>Équipe<select required value={form.team_id} onChange={e=>{const t=teams.find(x=>x.id===e.target.value);setForm({...form,team_id:e.target.value,season:t?.season||form.season})}}><option value="">Sélectionner</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Saison<input required value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label><label>Jour<select value={form.weekday} onChange={e=>setForm({...form,weekday:Number(e.target.value)})}>{weekdays.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label>Début<input required type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></label><label>Fin<input required type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></label><label>Salle<input value={form.location_name||''} onChange={e=>setForm({...form,location_name:e.target.value})} placeholder="Salle non renseignée"/></label><label>Valide du<input required type="date" value={form.valid_from} onChange={e=>setForm({...form,valid_from:e.target.value})}/></label><label>Valide jusqu’au<input type="date" value={form.valid_until||''} onChange={e=>setForm({...form,valid_until:e.target.value||null})}/></label><div className="operational-planning__form-actions"><button type="submit">{editing?'Confirmer la modification':'Créer le créneau'}</button>{editing&&<button type="button" onClick={()=>{setEditing(false);setForm(createEmptySlot())}}>Annuler</button>}</div></form>}
    <section className="operational-planning__list"><h2>Semaine type</h2>{loading?<p>Chargement…</p>:filtered.length===0?<p>Aucun créneau partagé pour ces filtres.</p>:weekdays.map((day,index)=>{const rows=filtered.filter(s=>s.weekday===index+1);return rows.length?<section key={day}><h3>{day}</h3>{rows.map(slot=><article key={slot.id} className={conflictIds.has(slot.id)?'has-conflict':''}><div><strong>{slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)} · {slot.team?.name||'Équipe'}</strong><span>{slot.location_name||'Salle non renseignée'} · {slot.season}</span><small>Du {slot.valid_from}{slot.valid_until?` au ${slot.valid_until}`:' sans date de fin'}</small>{conflictIds.has(slot.id)&&<b>Chevauchement de salle détecté</b>}</div><nav><Link to={`${teamBasePath}/${slot.team_id}`}>Équipe</Link>{canManage&&<><button onClick={()=>edit(slot)}>Modifier</button><button onClick={()=>disable(slot.id)}>Désactiver</button></>}</nav></article>)}</section>:null})}</section>
  </main>
}
