import type {
  TutorialAudience,
  TutorialCategory,
  TutorialItem,
  TutorialRoleCapability,
} from "../../types/tutorials";

export const tutorialAudienceLabels: Record<TutorialAudience, string> = {
  admin: "Admin",
  responsable_technique: "Responsable technique",
  coach: "Coach",
  dirigeant: "Dirigeant",
  parent_referent: "Parent référent",
  membre: "Membre",
  tous: "Tous",
};

export const tutorialCategoryLabels: Record<TutorialCategory, string> = {
  studio_editorial: "Studio éditorial",
  createur_seance: "Créateur de séance",
  import_effectifs: "Import effectifs",
  presences_evaluations: "Présences & évaluations",
  bibliotheque: "Bibliothèque",
  exports: "Exports",
  ocr_pieces_jointes: "OCR & pièces jointes",
  roles_permissions: "Rôles & droits",
  faq: "FAQ",
};

export const tutorialCategoryOrder: TutorialCategory[] = [
  "studio_editorial",
  "createur_seance",
  "import_effectifs",
  "presences_evaluations",
  "bibliotheque",
  "exports",
  "ocr_pieces_jointes",
  "roles_permissions",
  "faq",
];

export const tutorialAudienceOrder: TutorialAudience[] = [
  "tous",
  "admin",
  "responsable_technique",
  "coach",
  "dirigeant",
  "parent_referent",
  "membre",
];

export const roleCapabilityMatrix: TutorialRoleCapability[] = [
  {
    module: "Studio éditorial documentaire",
    admin: "Créer, transformer, contrôler, exporter",
    responsable_technique: "Lecture aide uniquement",
    coach: "Non",
    dirigeant: "Non",
    parent_referent: "Non",
    membre: "Non",
  },
  {
    module: "Bibliothèque documentaire",
    admin: "Accès complet",
    responsable_technique: "Accès complet hors réglages sensibles",
    coach: "Documents coachs et équipes",
    dirigeant: "Documents club et cadres",
    parent_referent: "Documents familles et logistique",
    membre: "Documents publics ou partagés",
  },
  {
    module: "Créateur de séances",
    admin: "Créer et administrer",
    responsable_technique: "Créer et superviser",
    coach: "Créer, modifier, exporter",
    dirigeant: "Consultation si partagé",
    parent_referent: "Non",
    membre: "Non",
  },
  {
    module: "Effectifs, présences, évaluations",
    admin: "Accès complet",
    responsable_technique: "Suivi sportif complet",
    coach: "Gérer ses équipes",
    dirigeant: "Synthèse et pilotage",
    parent_referent: "Présences utiles et logistique",
    membre: "Non",
  },
  {
    module: "OCR, qualité, exports avancés",
    admin: "Accès complet",
    responsable_technique: "Non",
    coach: "Exports séance autorisés",
    dirigeant: "Consultation exports publiés",
    parent_referent: "Documents utiles publiés",
    membre: "Documents publics",
  },
];

export const tutorialItems: TutorialItem[] = [
  {
    id: "creer-document-bcvb",
    title: "Créer un document BCVB publiable",
    subtitle: "Workflow complet du cadrage à l’export, réservé au pilotage documentaire admin.",
    category: "studio_editorial",
    audience: ["admin", "responsable_technique"],
    level: "intermédiaire",
    estimatedTime: "12 min",
    priority: "haute",
    impact: "fort",
    complexity: "faible",
    status: "publié",
    forWhat: "Produire un document BCVB clair, structuré, contrôlé et prêt à diffuser.",
    why: "Réduire les erreurs de production, les oublis de sections et les demandes d’aide au moment de publier.",
    how: "Suivre le parcours cadrage, source, plan, production guidée, contenu préparé, qualité, prévisualisation puis export.",
    evolution: "Ajouter un mode guidé vidéo et des exemples par famille documentaire.",
    implementation: "Page tutoriel, checklist interactive, lien direct vers le Studio éditorial et rappel du score qualité.",
    relatedRoutes: ["/admin/studio-editorial", "/admin/documents/nouveau", "/admin/qualite-exports"],
    steps: [
      {
        id: "cadre",
        title: "Définir le cadrage",
        description: "Choisis la famille, la catégorie, l’audience, la saison et l’objectif du document.",
        actionLabel: "Ouvrir le Studio",
        expectedResult: "Le document cible est lisible avant toute production documentaire.",
      },
      {
        id: "source",
        title: "Ajouter la source",
        description: "Colle le texte, importe un PDF, une image scannée ou reprends une source de bibliothèque.",
        expectedResult: "Le contenu brut est disponible pour construire un plan cohérent.",
      },
      {
        id: "plan",
        title: "Valider le plan éditorial",
        description: "Contrôle les sections proposées et complète les manques avant de préparer le cadre de rédaction.",
        expectedResult: "Le plan contient les blocs indispensables à une publication club.",
      },
      {
        id: "production",
        title: "Produire un brouillon structuré",
        description: "Prépare le cadre de rédaction, colle le contenu préparé, puis consolide les versions si nécessaire.",
        warning: "Ne publie jamais un brouillon brut sans contrôle qualité.",
      },
      {
        id: "qualite",
        title: "Corriger et publier",
        description: "Lance le contrôle qualité, applique les corrections massives, prévisualise puis exporte.",
        expectedResult: "Le document atteint le niveau de publication attendu et peut être enregistré en bibliothèque.",
      },
    ],
    checklist: [
      "Famille documentaire renseignée",
      "Audience et saison vérifiées",
      "Source complète ou OCR validé",
      "Plan éditorial relu",
      "Score qualité contrôlé",
      "PDF ou source exporté",
      "Bibliothèque mise à jour sans écraser l’original",
    ],
  },
  {
    id: "creer-fiche-seance",
    title: "Créer une fiche séance terrain",
    subtitle: "Préparer une séance exploitable en gymnase avec situations, terrain et exports.",
    category: "createur_seance",
    audience: ["admin", "responsable_technique", "coach"],
    level: "débutant",
    estimatedTime: "10 min",
    priority: "haute",
    impact: "fort",
    complexity: "moyenne",
    status: "publié",
    forWhat: "Former les coachs à produire une fiche séance complète et directement utilisable.",
    why: "Assurer une utilisation réelle en gymnase avec objectifs, rotations, critères et schémas lisibles.",
    how: "Créer la séance, ajouter les situations, dessiner le terrain tactique, puis exporter en PDF ou image.",
    evolution: "Ajouter un assistant intégré avec modèles préremplis par catégorie et objectif.",
    implementation: "Tutoriel pas à pas, popovers contextuels et raccourcis vers la bibliothèque de situations.",
    relatedRoutes: ["/coach/seances", "/coach/seances/bibliotheque", "/coach/situations/bibliotheque"],
    steps: [
      {
        id: "infos",
        title: "Renseigner l’objectif de séance",
        description: "Indique l’équipe, la catégorie, la durée, le thème principal et l’intention coach.",
        expectedResult: "La séance a un cap clair avant d’ajouter les situations.",
      },
      {
        id: "situations",
        title: "Ajouter les situations",
        description: "Compose l’échauffement, le corps de séance, la forme jouée et le retour au calme.",
      },
      {
        id: "terrain",
        title: "Dessiner le terrain",
        description: "Place joueurs, défenseurs, coachs, cônes, zones, passes, dribbles et déplacements.",
        expectedResult: "Le schéma terrain correspond au rendu exporté.",
      },
      {
        id: "criteres",
        title: "Écrire les critères de réussite",
        description: "Ajoute les consignes, observables, variantes et points de vigilance.",
      },
      {
        id: "export",
        title: "Exporter la fiche",
        description: "Télécharge la séance au format PDF ou image pour l’imprimer ou la partager.",
      },
    ],
    checklist: [
      "Objectif sportif clair",
      "Temps par situation cohérent",
      "Schéma terrain lisible",
      "Critères de réussite présents",
      "Variantes prévues",
      "Export vérifié",
    ],
  },
  {
    id: "importer-effectif",
    title: "Importer un effectif CSV ou Excel",
    subtitle: "Passer d’un fichier brut à un effectif propre, mappé et affecté à une équipe.",
    category: "import_effectifs",
    audience: ["admin", "responsable_technique", "coach"],
    level: "débutant",
    estimatedTime: "8 min",
    priority: "haute",
    impact: "fort",
    complexity: "faible",
    status: "publié",
    forWhat: "Importer rapidement une liste de joueurs sans double saisie.",
    why: "Éviter les erreurs de données, les doublons et les joueurs affectés à la mauvaise équipe.",
    how: "Choisir un fichier, mapper les colonnes, prévisualiser, corriger les alertes puis valider l’import.",
    evolution: "Détection automatique des exports Kalisport et FFBB.",
    implementation: "Tutoriel avec exemple de fichier, mapping guidé, prévisualisation et rapport d’import.",
    relatedRoutes: ["/effectifs", "/effectifs/import", "/admin/import-joueurs"],
    steps: [
      {
        id: "fichier",
        title: "Sélectionner le fichier",
        description: "Dépose un CSV, XLS ou XLSX contenant au minimum nom, prénom et catégorie.",
      },
      {
        id: "mapping",
        title: "Associer les colonnes",
        description: "Relie les colonnes du fichier aux champs BCVB : joueur, naissance, licence, contact, équipe.",
      },
      {
        id: "preview",
        title: "Contrôler la prévisualisation",
        description: "Vérifie les lignes incomplètes, les doublons possibles et les contacts familles.",
      },
      {
        id: "affectation",
        title: "Affecter à une équipe",
        description: "Choisis une équipe existante ou crée l’affectation de saison.",
      },
      {
        id: "validation",
        title: "Valider l’import",
        description: "Importe uniquement après correction des alertes bloquantes.",
        expectedResult: "Les joueurs sont disponibles pour présences, évaluations et équipes.",
      },
    ],
    checklist: [
      "Fichier au format CSV/XLS/XLSX",
      "Colonnes obligatoires détectées",
      "Doublons relus",
      "Équipe et saison sélectionnées",
      "Contacts familles vérifiés",
      "Rapport d’import conservé",
    ],
  },
  {
    id: "faire-appel-evaluer",
    title: "Faire l’appel et compléter les évaluations",
    subtitle: "Uniformiser le suivi joueur : présences, motifs, scores, axes de progrès.",
    category: "presences_evaluations",
    audience: ["admin", "responsable_technique", "coach", "parent_referent"],
    level: "intermédiaire",
    estimatedTime: "9 min",
    priority: "moyenne",
    impact: "fort",
    complexity: "moyenne",
    status: "publié",
    forWhat: "Expliquer le suivi joueur de la feuille d’appel à la synthèse d’évaluation.",
    why: "Uniformiser les pratiques coachs et disposer d’indicateurs fiables en commission sportive.",
    how: "Créer ou sélectionner une séance, qualifier chaque présence, puis compléter les domaines d’évaluation.",
    evolution: "Mode démo avec équipe fictive et parcours de formation interne.",
    implementation: "Tutoriels appel et évaluation, exemples de motifs et grille d’objectifs joueur.",
    relatedRoutes: ["/presences", "/evaluations", "/coach/evaluations", "/parents-referents/presences"],
    steps: [
      {
        id: "session",
        title: "Choisir la séance ou le match",
        description: "Sélectionne l’événement concerné et vérifie que le bon effectif est affiché.",
      },
      {
        id: "appel",
        title: "Qualifier chaque joueur",
        description: "Présent, absent excusé, absent non excusé, retard ou blessure avec commentaire utile.",
      },
      {
        id: "validation",
        title: "Valider la feuille",
        description: "Le coach valide, le parent référent peut aider sur la logistique selon ses droits.",
      },
      {
        id: "evaluation",
        title: "Compléter l’évaluation",
        description: "Renseigne technique, défense, intensité, attitude et compréhension du jeu.",
      },
      {
        id: "synthese",
        title: "Préparer la synthèse",
        description: "Vérifie les objectifs, les joueurs à relancer et les évaluations à mettre à jour.",
      },
    ],
    checklist: [
      "Bon événement sélectionné",
      "Motifs d’absence explicites",
      "Retards qualifiés",
      "Évaluation complétée par domaine",
      "Objectifs joueur mis à jour",
      "Synthèse équipe prête",
    ],
  },
  {
    id: "comprendre-roles-droits",
    title: "Comprendre les droits par rôle",
    subtitle: "Clarifier ce que chaque profil peut voir, créer, modifier ou exporter.",
    category: "roles_permissions",
    audience: ["tous"],
    level: "débutant",
    estimatedTime: "6 min",
    priority: "moyenne",
    impact: "moyen",
    complexity: "moyenne",
    status: "publié",
    forWhat: "Clarifier les droits admin, coach, dirigeant, parent référent et membre.",
    why: "Limiter les incompréhensions et sécuriser la plateforme pendant les réunions club.",
    how: "Lire la matrice, identifier son rôle, puis utiliser uniquement les modules visibles dans le menu.",
    evolution: "Onboarding par rôle au premier login.",
    implementation: "Matrice des droits intégrée, badges et messages de périmètre sur les modules sensibles.",
    relatedRoutes: ["/dashboard", "/bibliotheque", "/faq"],
    steps: [
      {
        id: "profil",
        title: "Identifier son profil",
        description: "Le rôle affiché dans la barre supérieure conditionne les menus visibles.",
      },
      {
        id: "modules",
        title: "Lire les modules autorisés",
        description: "Le menu latéral masque les rubriques hors périmètre pour éviter les actions impossibles.",
      },
      {
        id: "admin",
        title: "Repérer les modules admin",
        description: "Studio, OCR, qualité documentaire, exports avancés et administration restent réservés à l’admin.",
      },
      {
        id: "aide",
        title: "Utiliser FAQ et tutoriels",
        description: "En cas de blocage, vérifier d’abord la rubrique d’aide puis remonter le cas à l’admin.",
      },
    ],
    checklist: [
      "Rôle confirmé",
      "Modules visibles compris",
      "Périmètre admin identifié",
      "Accès bibliothèque vérifié",
      "FAQ consultée si blocage",
    ],
  },
  {
    id: "utiliser-bibliotheque",
    title: "Retrouver et transformer un document",
    subtitle: "Rechercher, filtrer, prévisualiser, télécharger ou transformer une ressource BCVB.",
    category: "bibliotheque",
    audience: ["tous"],
    level: "débutant",
    estimatedTime: "7 min",
    priority: "moyenne",
    impact: "fort",
    complexity: "faible",
    status: "publié",
    forWhat: "Faire de la bibliothèque un centre de ressources exploitable par chaque rôle.",
    why: "Éviter les documents introuvables, les versions obsolètes et les téléchargements morts.",
    how: "Chercher par texte, filtrer par famille, audience, saison ou statut, puis ouvrir la prévisualisation.",
    evolution: "Recherche sémantique enrichie et suggestions par rôle.",
    implementation: "Guide de recherche, lecture des badges et transformation en document BCVB pour les profils autorisés.",
    relatedRoutes: ["/bibliotheque", "/documents-utiles", "/documents-club"],
    steps: [
      {
        id: "search",
        title: "Lancer une recherche",
        description: "Tape un mot du titre, de la catégorie, du résumé, du tag ou de la saison.",
      },
      {
        id: "filters",
        title: "Appliquer les filtres",
        description: "Combine famille documentaire, audience, statut qualité et type de fichier.",
      },
      {
        id: "preview",
        title: "Prévisualiser",
        description: "Ouvre la fiche document pour lire les métadonnées et l’aperçu de contenu.",
      },
      {
        id: "download",
        title: "Télécharger ou générer",
        description: "Télécharge le PDF ou la source disponible. Si le PDF manque, utilise le bouton de génération.",
      },
      {
        id: "transform",
        title: "Transformer sans écraser",
        description: "Créer un nouveau document dérivé conserve l’original et envoie la source vers le Studio.",
      },
    ],
    checklist: [
      "Recherche testée",
      "Filtres cohérents",
      "Droits d’accès compris",
      "Aperçu ouvert",
      "Téléchargement vérifié",
      "Transformation réservée aux profils autorisés",
    ],
  },
  {
    id: "exports-bcvb",
    title: "Utiliser les exports PDF, Markdown, PNG et SVG",
    subtitle: "Choisir le bon format selon l’usage : impression, archive, partage ou schéma terrain.",
    category: "exports",
    audience: ["admin", "responsable_technique", "coach", "dirigeant"],
    level: "intermédiaire",
    estimatedTime: "6 min",
    priority: "moyenne",
    impact: "fort",
    complexity: "faible",
    status: "publié",
    forWhat: "Savoir quel export utiliser selon le besoin opérationnel.",
    why: "Éviter les mauvais formats, les pertes de source et les PDF générés trop tôt.",
    how: "Contrôler le rendu écran, choisir PDF pour diffusion, Markdown pour source, PNG/SVG pour schémas.",
    evolution: "Historique des exports et packs commission sportive.",
    implementation: "Panneau de bonnes pratiques avec routes vers qualité documentaire, bibliothèque et créateur de séance.",
    relatedRoutes: ["/admin/qualite-exports", "/bibliotheque", "/coach/seances"],
    steps: [
      {
        id: "pdf",
        title: "Exporter en PDF",
        description: "Utilise le PDF pour imprimer, partager ou publier un document finalisé.",
      },
      {
        id: "markdown",
        title: "Conserver la source Markdown",
        description: "Télécharge la source pour retravailler le document sans perdre sa structure.",
      },
      {
        id: "image",
        title: "Exporter les schémas",
        description: "Choisis PNG pour une image rapide, SVG pour un rendu vectoriel fidèle.",
      },
      {
        id: "controle",
        title: "Contrôler avant diffusion",
        description: "Vérifie que l’export correspond au rendu écran et que la version est la dernière.",
      },
    ],
    checklist: [
      "Rendu écran relu",
      "Format adapté choisi",
      "Version actuelle identifiée",
      "PDF généré uniquement si besoin",
      "Source conservée si document de référence",
    ],
  },
  {
    id: "ocr-pieces-jointes",
    title: "Importer OCR, PDF scannés et pièces jointes",
    subtitle: "Transformer une source brute en contenu exploitable par le Studio éditorial.",
    category: "ocr_pieces_jointes",
    audience: ["admin"],
    level: "avancé",
    estimatedTime: "8 min",
    priority: "haute",
    impact: "fort",
    complexity: "moyenne",
    status: "publié",
    forWhat: "Utiliser les fichiers scannés, images, PDF ou DOCX comme sources documentaires.",
    why: "Récupérer les contenus existants du club sans ressaisie manuelle.",
    how: "Importer la pièce, extraire le texte, relire l’OCR, puis envoyer vers le Studio éditorial.",
    evolution: "File d’attente OCR, détection automatique des tableaux et classement par document source.",
    implementation: "Module admin avec dépôt, statut d’extraction, prévisualisation et bouton envoyer vers Studio.",
    relatedRoutes: ["/admin/ocr-pieces-jointes", "/admin/documents/transformer"],
    steps: [
      {
        id: "upload",
        title: "Déposer la pièce jointe",
        description: "Ajoute un PDF, une image scannée ou un document source depuis le module admin.",
      },
      {
        id: "ocr",
        title: "Lancer ou vérifier l’OCR",
        description: "Contrôle le texte extrait, surtout les titres, tableaux et noms propres.",
      },
      {
        id: "nettoyage",
        title: "Nettoyer la source",
        description: "Supprime les artefacts et reformate les sections avant production.",
      },
      {
        id: "studio",
        title: "Envoyer vers le Studio",
        description: "Le contenu source est repris sans écraser le fichier original.",
      },
    ],
    checklist: [
      "Fichier lisible",
      "OCR relu",
      "Source nettoyée",
      "Métadonnées ajoutées",
      "Envoi Studio validé",
    ],
  },
  {
    id: "reprendre-travail",
    title: "Reprendre un travail sauvegardé",
    subtitle: "Retrouver le dernier document, la dernière séance, planification ou import en cours.",
    category: "faq",
    audience: ["tous"],
    level: "débutant",
    estimatedTime: "4 min",
    priority: "moyenne",
    impact: "moyen",
    complexity: "faible",
    status: "publié",
    forWhat: "Continuer un travail sans repartir de zéro.",
    why: "Éviter la perte de temps après une réunion, une séance ou une interruption de navigateur.",
    how: "Utiliser le tableau de bord, les cartes de reprise, les brouillons et la bibliothèque.",
    evolution: "Historique personnel par utilisateur et notifications de brouillons inachevés.",
    implementation: "Guide court relié au tableau de bord et aux modules principaux.",
    relatedRoutes: ["/dashboard", "/admin/studio-editorial", "/coach/seances", "/effectifs"],
    steps: [
      {
        id: "dashboard",
        title: "Ouvrir le tableau de bord",
        description: "Consulte les cartes de reprise : document, séance, planification ou effectif.",
      },
      {
        id: "module",
        title: "Retourner dans le bon module",
        description: "La reprise ouvre le module concerné avec le contexte le plus récent.",
      },
      {
        id: "controle",
        title: "Vérifier avant de continuer",
        description: "Relis les dernières données sauvegardées avant de produire ou exporter.",
      },
    ],
    checklist: [
      "Tableau de bord consulté",
      "Dernier module retrouvé",
      "Données relues",
      "Export relancé si nécessaire",
    ],
  },
];

export function findTutorialById(tutorialId?: string) {
  return tutorialItems.find((tutorial) => tutorial.id === tutorialId) ?? tutorialItems[0];
}
