export const SITE_ROLES = [
  'admin',
  'coach',
  'dirigeant',
  'responsable_technique',
  'parent_referent',
  'team_staff',
  'joueur',
  'parent',
  'benevole',
  'arbitre',
  'otm',
  'member',
  'membre',
]

const allRoles = SITE_ROLES
const adminOnly = ['admin', 'responsable_technique']
const helpRoles = ['admin', 'coach', 'dirigeant', 'responsable_technique', 'parent_referent', 'team_staff', 'joueur', 'parent', 'benevole', 'arbitre', 'otm', 'member', 'membre']
const libraryRoles = helpRoles
const coachRoles = ['admin', 'coach', 'responsable_technique']

export const SITE_GROUPS = [
  'Tableau de bord',
  'Production',
  'Documents',
  'Terrain / coachs',
  'Espaces dédiés',
  'Administration',
]

export const SITE_CATEGORIES = [
  {
    id: 'dashboard',
    label: 'Tableau de bord',
    shortLabel: 'Dashboard',
    group: 'Tableau de bord',
    path: '/dashboard',
    color: 'green',
    roles: allRoles,
    adminOnly: false,
    description: 'Accueil personnalisé selon le profil connecté.',
    purpose: 'Orienter chaque membre vers les modules réellement utiles à son rôle.',
    mainActions: ['Consulter les raccourcis', 'Reprendre les actions récentes', 'Accéder aux priorités du moment'],
    subModules: [],
  },
  {
    id: 'editorial-studio',
    label: 'Studio éditorial documentaire',
    shortLabel: 'Studio',
    group: 'Production',
    path: '/admin/studio-editorial',
    color: 'green',
    roles: adminOnly,
    adminOnly: true,
    description: 'Création documentaire qualité éditeur réservée à l’administrateur.',
    purpose: 'Produire, transformer et structurer les documents de référence BCVB.',
    mainActions: ['Créer un document', 'Transformer une source', 'Préparer une publication'],
    subModules: ['admin/documents/nouveau', 'admin/documents/transformer', 'admin/studio-editorial'],
  },
  {
    id: 'quality-exports',
    label: 'Qualité documentaire et exports',
    shortLabel: 'Qualité',
    group: 'Production',
    path: '/admin/qualite-exports',
    color: 'green',
    roles: adminOnly,
    adminOnly: true,
    description: 'Contrôle qualité, conformité BCVB, exports PDF et publication.',
    purpose: 'Garantir que les documents diffusés soient lisibles, complets et exploitables.',
    mainActions: ['Contrôler un score qualité', 'Exporter un PDF', 'Publier en bibliothèque'],
    subModules: ['admin/controle-qualite', 'admin/import-export'],
  },
  {
    id: 'ocr-attachments',
    label: 'OCR et pièces jointes',
    shortLabel: 'OCR',
    group: 'Production',
    path: '/admin/ocr-pieces-jointes',
    color: 'blue',
    roles: adminOnly,
    adminOnly: true,
    description: 'Chaîne complète PDF texte, scans, images, OCR, nettoyage, prévisualisation et transformation BCVB.',
    purpose: 'Transformer les pièces brutes en matière documentaire exploitable dans le Studio éditorial.',
    mainActions: ['Importer une source', 'Détecter le type', 'Nettoyer OCR', 'Transformer en BCVB Rich Markdown'],
    subModules: ['admin/documents/transformer'],
  },
  {
    id: 'library',
    label: 'Bibliothèque documentaire',
    shortLabel: 'Bibliothèque',
    group: 'Documents',
    path: '/bibliotheque',
    color: 'green',
    roles: libraryRoles,
    adminOnly: false,
    description: 'Documents club, contenus cadres, ressources sportives et documents utiles.',
    purpose: 'Centraliser les ressources accessibles selon le niveau de droits.',
    mainActions: ['Ouvrir un document', 'Télécharger une ressource', 'Retrouver les documents utiles'],
    subModules: ['documents-utiles', 'documents-club', 'library/:id', 'documents/:id'],
  },
  {
    id: 'tutorials',
    label: 'Tutoriels d’utilisation',
    shortLabel: 'Tutoriels',
    group: 'Documents',
    path: '/tutoriels/plateforme',
    color: 'blue',
    roles: helpRoles,
    adminOnly: false,
    description: 'Guides d’utilisation par profil : documents, séances, imports, présences, évaluations et exports.',
    purpose: 'Aider les utilisateurs à comprendre les modules, les droits et les bons gestes opérationnels.',
    mainActions: ['Chercher un tutoriel', 'Suivre une checklist', 'Comprendre les rôles', 'Reprendre un travail'],
    subModules: ['tutoriels', 'tutoriels/plateforme', 'tutoriels/createur-document'],
  },
  {
    id: 'faq',
    label: 'FAQ plateforme BCVB',
    shortLabel: 'FAQ',
    group: 'Documents',
    path: '/faq',
    color: 'blue',
    roles: helpRoles,
    adminOnly: false,
    description: 'Centre d’aide filtré par rôle, connecté aux erreurs, documents, exports, séances et imports.',
    purpose: 'Éviter les blocages, expliquer les droits et orienter vers les tutoriels utiles.',
    mainActions: ['Rechercher une réponse', 'Filtrer par rôle', 'Diagnostiquer une erreur', 'Ouvrir un tutoriel lié'],
    subModules: ['faq?error=QUALITY_SCORE_BLOCKED', 'faq?error=IMPORT_VALIDATION_FAILED', 'faq?error=COURT_RENDER_EMPTY'],
  },
  {
    id: 'sessions',
    label: 'Créateur de séances',
    shortLabel: 'Séances',
    group: 'Terrain / coachs',
    path: '/coach/seances',
    color: 'green',
    roles: coachRoles,
    adminOnly: false,
    description: 'Création de séances terrain avec objectifs, situations et exports.',
    purpose: 'Permettre aux coachs de préparer des séances claires et exploitables.',
    mainActions: ['Nouvelle séance', 'Importer séance complète', 'Importer situation pédagogique', 'Exporter PDF'],
    subModules: [
      'coach/seances/bibliotheque',
      'coach/situations/bibliotheque',
      'admin/gestion-seances',
      'admin/gestion-situations',
      'seances',
      'seances/nouveau',
      'generateur',
    ],
  },
  {
    id: 'planning',
    label: 'Planifications sportives',
    shortLabel: 'Planifications',
    group: 'Terrain / coachs',
    path: '/planifications',
    color: 'blue',
    roles: coachRoles,
    adminOnly: false,
    description: 'Cycles sportifs, progression annuelle et objectifs par équipe.',
    purpose: 'Structurer la saison selon la catégorie, le niveau et l’identité BCVB.',
    mainActions: ['Créer une planification', 'Adapter les cycles', 'Exporter le suivi'],
    subModules: ['coach/planifications', 'planning'],
  },
  {
    id: 'teams-management',
    label: 'Gestion des équipes',
    shortLabel: 'Équipes',
    group: 'Terrain / coachs',
    path: '/equipes',
    color: 'blue',
    roles: coachRoles,
    adminOnly: false,
    description: 'Équipes, staffs, catégories, alertes et organisation sportive.',
    purpose: 'Garder une vision opérationnelle des groupes coachés.',
    mainActions: ['Voir les équipes', 'Suivre les alertes', 'Accéder aux outils équipe'],
    subModules: ['coach/equipes', 'club/equipes'],
  },
  {
    id: 'rosters',
    label: 'Effectifs et équipes',
    shortLabel: 'Effectifs',
    group: 'Terrain / coachs',
    path: '/effectifs',
    color: 'blue',
    roles: coachRoles,
    adminOnly: false,
    description: 'Import CSV/Excel, mapping, contrôle doublons et affectation équipe.',
    purpose: 'Mettre à jour les joueurs et composer les groupes de travail.',
    mainActions: ['Importer CSV/Excel', 'Mapper les colonnes', 'Valider les joueurs'],
    subModules: ['effectifs/import', 'admin/import-joueurs'],
  },
  {
    id: 'attendance',
    label: 'Présences et absences',
    shortLabel: 'Présences',
    group: 'Terrain / coachs',
    path: '/presences',
    color: 'blue',
    roles: coachRoles,
    adminOnly: false,
    description: 'Feuille d’appel, absences excusées, retards et exports de suivi.',
    purpose: 'Suivre l’assiduité et disposer d’un historique utile pour le staff.',
    mainActions: ['Faire l’appel', 'Qualifier une absence', 'Exporter en CSV'],
    subModules: ['coach/presences', 'equipe/presences'],
  },
  {
    id: 'evaluations',
    label: 'Évaluations joueurs',
    shortLabel: 'Évaluations',
    group: 'Terrain / coachs',
    path: '/evaluations',
    color: 'blue',
    roles: coachRoles,
    adminOnly: false,
    description: 'Évaluations techniques, attitude, intensité et progression individuelle.',
    purpose: 'Aider les coachs à suivre les joueurs et objectiver les axes de progrès.',
    mainActions: ['Compléter une évaluation', 'Suivre une progression', 'Préparer une synthèse'],
    subModules: ['coach/evaluations', 'coach/joueurs/:id/progression'],
  },
  {
    id: 'leaders',
    label: 'Espace dirigeants',
    shortLabel: 'Dirigeants',
    group: 'Espaces dédiés',
    path: '/dirigeants',
    color: 'blue',
    roles: ['admin', 'dirigeant', 'responsable_technique'],
    adminOnly: false,
    description: 'Documents cadres, suivi des équipes et pilotage club.',
    purpose: 'Donner aux dirigeants une vue claire sans accès aux outils de production admin.',
    mainActions: ['Consulter les cadres', 'Lire les indicateurs', 'Préparer la commission'],
    subModules: ['club/tableau-de-bord', 'club/indicateurs', 'club/pilotage'],
  },
  {
    id: 'parent-ref',
    label: 'Espace parents référents',
    shortLabel: 'Parents réf.',
    group: 'Espaces dédiés',
    path: '/parents-referents',
    color: 'blue',
    roles: ['admin', 'responsable_technique', 'coach', 'parent_referent', 'team_staff'],
    adminOnly: false,
    description: 'Logistique, communication, événements et aide à l’organisation.',
    purpose: 'Limiter l’accès aux informations utiles aux familles référentes.',
    mainActions: ['Organiser un événement', 'Relayer une information', 'Consulter les documents utiles'],
    subModules: ['parent/referent', 'parents-referents/planifications', 'logistique', 'equipe/communication'],
  },
  {
    id: 'admin-settings',
    label: 'Paramètres et administration',
    shortLabel: 'Admin',
    group: 'Administration',
    path: '/parametres',
    color: 'green',
    roles: adminOnly,
    adminOnly: true,
    description: 'Pilotage global : rôles, permissions, saisons, standards, référentiels, exports et sécurité.',
    purpose: 'Administrer les accès, les standards club et les garde-fous sensibles de la plateforme.',
    mainActions: ['Configurer les rôles', 'Gérer la saison active', 'Régler les standards', 'Contrôler les exports'],
    subModules: ['admin', 'parametres', 'admin/membres', 'admin/inscriptions', 'admin/deblocages', 'admin/plateforme'],
  },
]

export function normalizeSiteRole(role) {
  if (role === 'membre') return 'member'
  if (role === 'technical_manager') return 'responsable_technique'
  return role || 'member'
}

export function canAccessCategory(category, role) {
  if (normalizeSiteRole(role) === 'admin') return true
  return category.roles.includes(normalizeSiteRole(role))
}

export function getVisibleSiteCategories(role) {
  return SITE_CATEGORIES.filter((category) => canAccessCategory(category, role))
}

export function getSiteCategoryById(id) {
  return SITE_CATEGORIES.find((category) => category.id === id)
}
