import type { FaqCategory, FaqItem, FaqRole } from "../../types/faq";

export const faqRoleLabels: Record<FaqRole, string> = {
  admin: "Admin",
  responsable_technique: "Responsable technique",
  coach: "Coach",
  dirigeant: "Dirigeant",
  parent_referent: "Parent référent",
  membre: "Membre",
  tous: "Tous",
};

export const faqCategoryLabels: Record<FaqCategory, string> = {
  acces: "Accès",
  documents: "Documents",
  studio_editorial: "Studio éditorial",
  seances: "Séances",
  effectifs: "Effectifs",
  presences: "Présences",
  evaluations: "Évaluations",
  exports: "Exports",
  ocr: "OCR",
  sauvegarde: "Sauvegarde",
  bibliotheque: "Bibliothèque",
  problemes: "Problèmes",
};

export const faqCategoryOrder: FaqCategory[] = [
  "acces",
  "documents",
  "studio_editorial",
  "bibliotheque",
  "exports",
  "ocr",
  "seances",
  "effectifs",
  "presences",
  "evaluations",
  "sauvegarde",
  "problemes",
];

export const faqRoleOrder: FaqRole[] = [
  "tous",
  "admin",
  "responsable_technique",
  "coach",
  "dirigeant",
  "parent_referent",
  "membre",
];

export const faqItems: FaqItem[] = [
  {
    id: "qui-peut-creer-modifier-telecharger",
    question: "Qui peut créer, modifier, télécharger ou consulter ?",
    shortAnswer: "Le menu et les actions dépendent du rôle connecté.",
    answer:
      "L’admin peut tout administrer. Le responsable technique supervise les contenus sportifs et les équipes. Le coach crée ses séances, gère ses effectifs, présences et évaluations. Le dirigeant consulte les documents cadres et le pilotage club. Le parent référent accède à la logistique, communication et présences utiles. Le membre voit les documents publics ou partagés.",
    category: "acces",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["droits", "rôles", "consultation", "modifier", "télécharger", "menu"],
    relatedRoutes: ["/dashboard", "/bibliotheque", "/tutoriels/plateforme"],
    relatedTutorialIds: ["comprendre-roles-droits"],
    relatedErrorCodes: ["AUTH_FORBIDDEN", "ROLE_SCOPE_LIMITED"],
  },
  {
    id: "pourquoi-module-invisible",
    question: "Pourquoi une rubrique n’apparaît pas dans mon menu ?",
    shortAnswer: "La navigation masque les modules hors périmètre pour éviter les erreurs.",
    answer:
      "Si une rubrique n’apparaît pas, ton rôle ne possède probablement pas les droits associés. Exemple : Studio éditorial, OCR, qualité documentaire, exports avancés et administration restent réservés à l’admin. Les coachs voient les modules terrain, les dirigeants le pilotage, les parents référents la logistique équipe.",
    category: "acces",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["menu", "navigation", "rôle", "module invisible", "accès refusé"],
    relatedRoutes: ["/dashboard", "/parametres"],
    relatedTutorialIds: ["comprendre-roles-droits"],
    relatedErrorCodes: ["AUTH_FORBIDDEN"],
  },
  {
    id: "document-non-publiable",
    question: "Pourquoi un document n’est pas publiable ?",
    shortAnswer: "Il manque des blocs obligatoires ou le score qualité est sous le seuil.",
    answer:
      "Un document peut être bloqué s’il manque un cadrage, une audience, une structure lisible, des situations exploitables, des critères, une conclusion, des métadonnées ou un niveau qualité suffisant. Le seuil conseillé est 95/100 pour publication club et 97/100 pour une référence durable BCVB.",
    category: "documents",
    roles: ["admin", "responsable_technique", "dirigeant"],
    priority: "haute",
    tags: ["publiable", "score qualité", "document", "contrôle qualité", "publication"],
    relatedRoutes: ["/admin/controle-qualite", "/admin/qualite-exports", "/admin/studio-editorial"],
    relatedTutorialIds: ["creer-document-bcvb"],
    relatedErrorCodes: ["QUALITY_SCORE_BLOCKED", "DOCUMENT_NOT_PUBLISHABLE"],
  },
  {
    id: "score-qualite-bloque",
    question: "Pourquoi le score qualité bloque l’export ou la publication ?",
    shortAnswer: "Le score protège la bibliothèque contre des documents incomplets.",
    answer:
      "Le contrôle qualité vérifie la structure, les titres, l’audience, les tableaux, les consignes, les situations, les imports et la lisibilité. Si le score bloque, utilise les corrections recommandées, complète les sections manquantes, puis relance le contrôle avant d’exporter ou d’enregistrer en bibliothèque.",
    category: "documents",
    roles: ["admin", "responsable_technique"],
    priority: "haute",
    tags: ["score", "qualité", "bloqué", "export", "publication", "correction"],
    relatedRoutes: ["/admin/controle-qualite", "/admin/qualite-exports"],
    relatedTutorialIds: ["creer-document-bcvb", "exports-bcvb"],
    relatedErrorCodes: ["QUALITY_SCORE_BLOCKED"],
  },
  {
    id: "transformer-document-bcvb",
    question: "Comment transformer un document existant en document BCVB ?",
    shortAnswer: "Depuis la bibliothèque, utilise “Transformer en document BCVB”.",
    answer:
      "Ouvre la bibliothèque, prévisualise le document, puis lance la transformation si ton rôle l’autorise. Le site crée un nouveau document dérivé avec sourceDocumentId, date de transformation et mode bcvb_upgrade. L’original n’est jamais écrasé.",
    category: "bibliotheque",
    roles: ["admin", "responsable_technique"],
    priority: "haute",
    tags: ["transformer", "bibliothèque", "document dérivé", "sourceDocumentId", "studio"],
    relatedRoutes: ["/bibliotheque", "/admin/documents/transformer", "/admin/studio-editorial"],
    relatedTutorialIds: ["utiliser-bibliotheque", "creer-document-bcvb"],
    relatedErrorCodes: ["DOCUMENT_SOURCE_MISSING"],
  },
  {
    id: "telecharger-document",
    question: "Pourquoi un document n’est pas téléchargeable ?",
    shortAnswer: "Le PDF ou la source peut manquer, mais l’interface doit expliquer l’état.",
    answer:
      "Si le PDF n’existe pas, le bouton doit indiquer “PDF à générer” et proposer la génération au lieu d’un bouton mort. Si la source Markdown manque, l’interface affiche “Source indisponible”. Vérifie aussi que ton rôle possède le droit de téléchargement sur ce document.",
    category: "exports",
    roles: ["tous"],
    priority: "haute",
    tags: ["télécharger", "PDF", "source", "markdown", "bouton", "bibliothèque"],
    relatedRoutes: ["/bibliotheque", "/admin/qualite-exports"],
    relatedTutorialIds: ["utiliser-bibliotheque", "exports-bcvb"],
    relatedErrorCodes: ["EXPORT_PDF_MISSING", "EXPORT_SOURCE_MISSING", "DOWNLOAD_FORBIDDEN"],
  },
  {
    id: "export-ne-fonctionne-pas",
    question: "Pourquoi un export PDF, Markdown, PNG ou SVG ne fonctionne pas ?",
    shortAnswer: "La source, le rendu ou les droits peuvent être incomplets.",
    answer:
      "Pour un document, vérifie que la source existe, que le score qualité autorise l’export et que le PDF est généré. Pour un schéma séance, vérifie que le terrain s’affiche à l’écran avant export : l’export doit reprendre le SVG visible. Si le droit est insuffisant, demande une validation admin.",
    category: "exports",
    roles: ["admin", "responsable_technique", "coach", "dirigeant"],
    priority: "haute",
    tags: ["export", "PDF", "Markdown", "PNG", "SVG", "terrain", "droits"],
    relatedRoutes: ["/admin/qualite-exports", "/coach/seances", "/bibliotheque"],
    relatedTutorialIds: ["exports-bcvb", "creer-fiche-seance"],
    relatedErrorCodes: ["EXPORT_FAILED", "EXPORT_PDF_MISSING", "COURT_EXPORT_FAILED"],
  },
  {
    id: "utiliser-ocr",
    question: "Comment utiliser OCR et pièces jointes ?",
    shortAnswer: "L’admin importe une source, relit l’OCR, puis l’envoie vers le Studio.",
    answer:
      "Dépose le PDF scanné, l’image ou le DOCX dans le module OCR. Relis le texte extrait, corrige les titres et tableaux si besoin, puis envoie la source vers le Studio éditorial. Le fichier original reste conservé comme pièce jointe.",
    category: "ocr",
    roles: ["admin"],
    priority: "haute",
    tags: ["OCR", "PDF scanné", "image", "pièce jointe", "source", "studio"],
    relatedRoutes: ["/admin/ocr-pieces-jointes", "/admin/documents/transformer"],
    relatedTutorialIds: ["ocr-pieces-jointes", "creer-document-bcvb"],
    relatedErrorCodes: ["OCR_EMPTY_TEXT", "OCR_UNSUPPORTED_FILE"],
  },
  {
    id: "importer-effectif-format",
    question: "Comment importer un effectif CSV ou Excel ?",
    shortAnswer: "Dépose le fichier, mappe les colonnes, prévisualise puis valide.",
    answer:
      "Le fichier doit contenir au minimum les informations joueur nécessaires : nom, prénom, catégorie ou équipe. Le module accepte CSV, XLS et XLSX. Après import, associe les colonnes aux champs BCVB, vérifie les erreurs, traite les doublons et affecte les joueurs à une équipe et une saison.",
    category: "effectifs",
    roles: ["admin", "responsable_technique", "coach"],
    priority: "haute",
    tags: ["effectif", "CSV", "Excel", "XLSX", "mapping", "import"],
    relatedRoutes: ["/effectifs/import", "/effectifs", "/admin/import-joueurs"],
    relatedTutorialIds: ["importer-effectif"],
    relatedErrorCodes: ["IMPORT_COLUMNS_MISSING", "IMPORT_FILE_UNSUPPORTED"],
  },
  {
    id: "corriger-erreur-import",
    question: "Comment corriger une erreur d’import d’effectif ?",
    shortAnswer: "Corrige d’abord les colonnes obligatoires, puis les doublons et affectations.",
    answer:
      "Si des colonnes manquent, complète le mapping. Si des dates ou licences sont invalides, corrige le fichier source ou la prévisualisation. En cas de doublon, compare nom, prénom, date de naissance et licence avant fusion. Ne valide pas tant qu’une alerte bloquante reste active.",
    category: "effectifs",
    roles: ["admin", "responsable_technique", "coach"],
    priority: "haute",
    tags: ["erreur import", "doublon", "colonnes", "mapping", "licence", "prévisualisation"],
    relatedRoutes: ["/effectifs/import"],
    relatedTutorialIds: ["importer-effectif"],
    relatedErrorCodes: ["IMPORT_COLUMNS_MISSING", "IMPORT_DUPLICATE_PLAYERS", "IMPORT_VALIDATION_FAILED"],
  },
  {
    id: "creer-seance",
    question: "Comment créer une séance ?",
    shortAnswer: "Le coach part d’un objectif, ajoute des situations, dessine le terrain et exporte.",
    answer:
      "Ouvre le créateur de séances, renseigne l’équipe, la catégorie, le thème et la durée. Ajoute les situations, écris les consignes, place les objets sur le terrain FIBA, puis exporte la fiche. Les coachs peuvent créer, modifier et exporter leurs séances selon leurs droits.",
    category: "seances",
    roles: ["admin", "responsable_technique", "coach"],
    priority: "moyenne",
    tags: ["séance", "coach", "terrain", "situation", "fiche", "export"],
    relatedRoutes: ["/coach/seances", "/coach/situations/bibliotheque"],
    relatedTutorialIds: ["creer-fiche-seance"],
  },
  {
    id: "terrain-schema-invisible",
    question: "Pourquoi un terrain ou un schéma n’apparaît pas correctement ?",
    shortAnswer: "Le schéma dépend du SVG terrain, des objets et du rendu écran.",
    answer:
      "Vérifie que le mode terrain est bien choisi, que le logo BCVB n’est pas utilisé comme fond, que les objets sont dans la zone visible et que le SVG n’est pas masqué par une colonne latérale. Pour les exports PNG/SVG, le rendu doit correspondre au terrain affiché à l’écran.",
    category: "seances",
    roles: ["admin", "responsable_technique", "coach"],
    priority: "moyenne",
    tags: ["terrain", "schéma", "SVG", "logo", "export", "canvas", "FastDraw"],
    relatedRoutes: ["/coach/seances"],
    relatedTutorialIds: ["creer-fiche-seance", "exports-bcvb"],
    relatedErrorCodes: ["COURT_RENDER_EMPTY", "COURT_EXPORT_FAILED"],
  },
  {
    id: "faire-appel",
    question: "Comment faire l’appel et qualifier les absences ?",
    shortAnswer: "Sélectionne l’événement, indique présent/absent/retard et ajoute le motif utile.",
    answer:
      "Dans Présences, choisis l’entraînement ou le match, puis qualifie chaque joueur. Les motifs utiles permettent de distinguer absence excusée, non excusée, blessure ou retard. Le parent référent peut aider sur les présences utiles et la logistique selon son périmètre.",
    category: "presences",
    roles: ["admin", "responsable_technique", "coach", "parent_referent"],
    priority: "moyenne",
    tags: ["appel", "présence", "absence", "retard", "motif", "parent référent"],
    relatedRoutes: ["/presences", "/coach/presences", "/parents-referents/presences"],
    relatedTutorialIds: ["faire-appel-evaluer"],
  },
  {
    id: "evaluations-visibles",
    question: "Qui peut voir ou compléter les évaluations joueurs ?",
    shortAnswer: "Les évaluations sont réservées aux coachs et responsables autorisés.",
    answer:
      "Les coachs complètent les évaluations de leurs équipes. L’admin et le responsable technique peuvent superviser. Les dirigeants consultent surtout des synthèses selon les droits. Les parents référents et membres ne voient pas les évaluations individuelles par défaut.",
    category: "evaluations",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["évaluation", "joueur", "coach", "dirigeant", "droits", "synthèse"],
    relatedRoutes: ["/evaluations", "/coach/evaluations", "/club/evaluations"],
    relatedTutorialIds: ["faire-appel-evaluer", "comprendre-roles-droits"],
    relatedErrorCodes: ["EVALUATION_FORBIDDEN"],
  },
  {
    id: "recuperer-brouillon",
    question: "Comment récupérer un brouillon ou un travail sauvegardé ?",
    shortAnswer: "Passe par le tableau de bord ou le module où le travail a été commencé.",
    answer:
      "Les travaux importants sont pensés pour être repris depuis les cartes du tableau de bord : dernier document, dernière séance, dernière planification ou dernier effectif importé. Avant de relancer une production ou un export, vérifie que les données restaurées correspondent bien à ton dernier état de travail.",
    category: "sauvegarde",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["brouillon", "autosave", "sauvegarde", "restaurer", "reprise", "dashboard"],
    relatedRoutes: ["/dashboard", "/admin/studio-editorial", "/coach/seances", "/effectifs"],
    relatedTutorialIds: ["reprendre-travail"],
    relatedErrorCodes: ["AUTOSAVE_DRAFT_FOUND", "DRAFT_RESTORE_AVAILABLE"],
  },
  {
    id: "travail-perdu",
    question: "Que faire si j’ai changé de page pendant un travail ?",
    shortAnswer: "Reviens dans le module concerné et cherche la reprise automatique.",
    answer:
      "Si tu quittes une page, commence par revenir dans le module d’origine. Le tableau de bord peut afficher la dernière action. Si rien n’est proposé, vérifie la bibliothèque ou le dernier export généré. Évite de réinitialiser le module tant que tu n’as pas confirmé que le brouillon n’est plus disponible.",
    category: "sauvegarde",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["page", "perdu", "autosave", "brouillon", "reset", "reprise"],
    relatedRoutes: ["/dashboard", "/tutoriels/plateforme"],
    relatedTutorialIds: ["reprendre-travail"],
    relatedErrorCodes: ["DRAFT_RESTORE_AVAILABLE"],
  },
  {
    id: "bibliotheque-document-invisible",
    question: "Pourquoi je ne vois pas un document dans la bibliothèque ?",
    shortAnswer: "La visibilité du document dépend du rôle, de l’audience et parfois de l’équipe.",
    answer:
      "Chaque document possède une visibilité : private, club, coaches, leaders, parents_ref ou public. Il peut aussi avoir une liste de rôles autorisés, un ownerId, une équipe ou une saison. Si le document est utile mais invisible, demande à l’admin de vérifier la visibilité et les rôles autorisés.",
    category: "bibliotheque",
    roles: ["tous"],
    priority: "moyenne",
    tags: ["bibliothèque", "document invisible", "visibility", "allowedRoles", "équipe", "saison"],
    relatedRoutes: ["/bibliotheque", "/documents-utiles", "/documents-club"],
    relatedTutorialIds: ["utiliser-bibliotheque", "comprendre-roles-droits"],
    relatedErrorCodes: ["DOCUMENT_ACCESS_DENIED", "ROLE_SCOPE_LIMITED"],
  },
  {
    id: "studio-documentaire-production",
    question: "Puis-je préparer plusieurs versions dans le Studio éditorial ?",
    shortAnswer: "Oui, l’admin peut préparer un cadre de rédaction puis consolider les contenus.",
    answer:
      "Le Studio éditorial permet de préparer un cadre de rédaction, de travailler une ou plusieurs propositions de contenu, puis de consolider une version finale. Après collage, relance toujours la normalisation, la correction massive et le contrôle qualité avant l’export.",
    category: "studio_editorial",
    roles: ["admin"],
    priority: "haute",
    tags: ["studio", "production guidée", "consolidation", "qualité", "document"],
    relatedRoutes: ["/admin/studio-editorial", "/admin/documents/nouveau"],
    relatedTutorialIds: ["creer-document-bcvb"],
    relatedErrorCodes: ["CONTENT_RESPONSE_EMPTY", "CONTENT_CONSOLIDATION_REQUIRED"],
  },
  {
    id: "probleme-inconnu",
    question: "Que faire si une erreur n’est pas expliquée ?",
    shortAnswer: "Note le module, l’action, le rôle et le message affiché.",
    answer:
      "Commence par rechercher un mot du message dans cette FAQ. Si rien ne correspond, note ton rôle, la route, le document ou l’équipe concernée, l’action exacte et le message. Cela permet à l’admin de rattacher l’erreur à un article FAQ ou à un correctif.",
    category: "problemes",
    roles: ["tous"],
    priority: "basse",
    tags: ["erreur", "support", "message", "blocage", "diagnostic"],
    relatedRoutes: ["/faq", "/tutoriels/plateforme"],
    relatedTutorialIds: ["comprendre-roles-droits"],
    relatedErrorCodes: ["UNKNOWN_ERROR"],
  },
];

export function findFaqById(faqId?: string | null) {
  return faqItems.find((item) => item.id === faqId) ?? null;
}
