import type { CategoryCode, CategoryKnowledgePack } from './types';

export const CATEGORY_KNOWLEDGE_PACKS: Record<CategoryCode, CategoryKnowledgePack> = {
	U7: {
		category: 'U7',
		title: 'U7 — Bouger au basket',
		learningStage: 'Découverte motrice, ballon, groupe et premières règles de vie.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'canada', 'usa'],
		majorPriorities: [
			'Motricité générale',
			'Manipulation du ballon',
			'Plaisir et engagement',
			'Vie collective',
			'Premières formes de coopération',
			'Défense ludique Homme à Homme',
			'Préparation progressive au U9',
		],
		coachableThemes: [
			'Courir, sauter, s’arrêter, se repérer',
			'Lancer, attraper, rouler',
			'Premiers rebonds / dribble',
			'Premières passes simples',
			'Viser une cible proche',
			'Suivre un adversaire sans contact',
			'Plateaux U7',
			'Relation parents / communication',
			'Routines de séance',
		],
		requiredSections: [
			'Finalité U7 dans le parcours BCVB',
			'Profil de l’enfant U7',
			'Principes pédagogiques',
			'Planification annuelle',
			'Structure de séance',
			'Situations pédagogiques thématiques',
			'Plateaux et parents',
			'Passerelle U7 vers U9',
		],
	},

	U9: {
		category: 'U9',
		title: 'U9 — S’amuser au basket',
		learningStage: 'Découverte des premières intentions de jeu.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'canada', 'usa'],
		majorPriorities: [
			'Jouer en avançant',
			'Dribbler avec intention',
			'Passer et se rendre disponible',
			'Défendre son joueur',
			'Comprendre les premières règles de jeu',
			'Transition offensive / défensive simple',
		],
		coachableThemes: [
			'1c1 simple',
			'Couloirs de course',
			'Démarquage de base',
			'Passe et va très simple',
			'Repli défensif',
			'Jeu réduit',
		],
		requiredSections: [
			'Finalité U9',
			'Priorités de formation',
			'Planification',
			'Situations pédagogiques',
			'Séances types',
			'Évaluation et passerelle U11',
		],
	},

	U11: {
		category: 'U11',
		title: 'U11 — Apprendre à jouer',
		learningStage: 'Premières lectures offensives, défensives et collectives.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'canada', 'usa', 'fiba'],
		majorPriorities: [
			'Recevoir prêt à jouer',
			'Dribbler pour attaquer un espace',
			'Passer pour améliorer l’action',
			'Défendre en Homme à Homme',
			'Lire l’espace et le partenaire',
			'Transition offensive et défensive',
		],
		coachableThemes: [
			'1c1',
			'2c1',
			'jeu sans ballon',
			'lecture espace libre',
			'défense sur porteur',
			'défense non-porteur initiale',
		],
		requiredSections: [
			'Finalité U11',
			'Identité BCVB U11',
			'Planification annuelle',
			'Situations par domaines',
			'Détection et posture club',
			'Passerelle U13',
		],
	},

	U13: {
		category: 'U13',
		title: 'U13 — S’entraîner à s’entraîner',
		learningStage: 'Stabiliser les fondamentaux et enrichir la lecture du jeu.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'fiba', 'europe', 'usa', 'canada'],
		majorPriorities: [
			'1c1 offensif et défensif',
			'Contact',
			'Lecture avantage / désavantage',
			'Jeu rapide',
			'Jeu sans ballon',
			'Aide défensive',
			'Rebond',
		],
		coachableThemes: [
			'Drive et kick',
			'Close-out',
			'Aide / reprise',
			'Transition 3c2 / 3c3',
			'2c2 et 3c3',
			'Fixer-passer',
		],
		requiredSections: [
			'Profil U13',
			'DLTA / maturation',
			'Planification annuelle',
			'Microcycles',
			'Banque de situations',
			'Évaluation joueur',
			'Préparation vers U15',
		],
	},

	U15: {
		category: 'U15',
		title: 'U15 — Se former pour performer',
		learningStage: 'Approfondir, complexifier, responsabiliser.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'fiba', 'europe', 'usa'],
		majorPriorities: [
			'Lecture collective',
			'Défense H-H structurée',
			'Écrans et réponses défensives',
			'Transition et rythme',
			'Autonomie tactique',
			'Coaching de match',
		],
		coachableThemes: [
			'Orange / Rouge / Vert',
			'300',
			'Screens',
			'Pick and roll novice',
			'Lecture des aides',
			'Défense du spacing',
		],
		requiredSections: [
			'Profil U15',
			'Identité tactique BCVB',
			'Planification',
			'Microcycles',
			'Banque d’exercices',
			'Match coaching',
			'Passerelle U18',
		],
	},

	U18: {
		category: 'U18',
		title: 'U18 — Consolider et performer',
		learningStage: 'Autonomie, exigence collective et compréhension stratégique.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'fiba', 'europe', 'usa'],
		majorPriorities: [
			'Tactique collective',
			'Responsabilisation',
			'Préparation physique',
			'Lecture avancée',
			'Gestion de match',
		],
		coachableThemes: [
			'Systèmes et principes',
			'Défenses collectives',
			'Prise de décision',
			'Préparation à l’entrée senior',
		],
		requiredSections: [
			'Profil U18',
			'Objectifs de performance',
			'Planification',
			'Microcycles',
			'Évaluation',
		],
	},

	U21: {
		category: 'U21',
		title: 'U21 — Transition vers le basket senior',
		learningStage: 'Passage vers l’autonomie compétitive.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'fiba', 'europe', 'usa'],
		majorPriorities: [
			'Performance',
			'Préparation au senior',
			'Responsabilité collective',
			'Exigence tactique',
		],
		coachableThemes: [
			'Rôles de jeu',
			'Préparation mentale',
			'Spécialisation progressive',
		],
		requiredSections: [
			'Profil U21',
			'Planification',
			'Passerelle senior',
		],
	},

	Seniors: {
		category: 'Seniors',
		title: 'Seniors — Performance et identité collective',
		learningStage: 'Optimisation du jeu et culture de performance.',
		recommendedDoctrines: ['bcvb', 'fiba', 'europe', 'usa'],
		majorPriorities: [
			'Performance collective',
			'Tactique',
			'Préparation spécifique',
			'Leadership',
		],
		coachableThemes: [
			'Plan de jeu',
			'Principes offensifs',
			'Principes défensifs',
			'Préparation d’adversaire',
		],
		requiredSections: [
			'Objectifs de performance',
			'Plan de jeu',
			'Planification',
			'Évaluation collective',
		],
	},

	General: {
		category: 'General',
		title: 'Général BCVB',
		learningStage: 'Cadres transversaux de club.',
		recommendedDoctrines: ['bcvb', 'ffbb', 'fiba'],
		majorPriorities: [
			'Cohérence club',
			'Formation interne',
			'Organisation',
			'Culture BCVB',
		],
		coachableThemes: [
			'Cadre coach',
			'Charte parent',
			'Projet sportif',
			'Formation des assistants',
		],
		requiredSections: [
			'Contexte',
			'Objectifs',
			'Organisation',
			'Applications concrètes',
		],
	},
};
