import type { DocumentFamily } from './documentIntentEngine'

export const EDITORIAL_STANDARDS = {
  cahier_technique: {
    label: 'Cahier technique',
    purpose: 'Document de référence durable pour structurer les contenus techniques d’une catégorie ou d’un thème.',
    format: 'A4 portrait',
    layout: 'Double colonne texte / schéma obligatoire pour les situations pédagogiques.',
    visualSignature: 'Titres forts, blocs autonomes, terrains intégrés, numérotation visible.',
    requiredSections: [
      'Couverture',
      'Identité BCVB',
      'Finalité technique',
      'Repères de développement',
      'Objectifs de formation',
      'Progression annuelle',
      'Situations pédagogiques',
      'Diagrammes terrain',
      'Critères de réussite',
      'Outils d’évaluation',
      'Synthèse coach',
    ],
    minimumTargets: { tables: 8, situations: 12, diagrams: 12, bcvbBlocks: 30 },
    qualityRules: [
      'Chaque situation doit être autonome.',
      'Chaque situation doit avoir un terrain intégré.',
      'Les tableaux doivent être structurés et typés.',
      'La progression doit être claire par période.',
    ],
  },
  guide_coach: {
    label: 'Guide du coach',
    purpose: 'Document de lecture profonde pour aider un coach à comprendre son rôle, sa catégorie et ses priorités.',
    format: 'A4 portrait',
    layout: 'Lecture profonde avec espaces blancs assumés, encarts latéraux, principes clés et synthèses.',
    visualSignature: 'Filet orange gauche sur les principes importants, encarts coach, hiérarchie éditoriale forte.',
    requiredSections: [
      'Couverture',
      'Identité catégorie',
      'Finalité dans le parcours joueur',
      'Profil des joueurs',
      'Rôle du coach',
      'Posture attendue',
      'Principes pédagogiques',
      'Organisation annuelle',
      'Séance type',
      'Situations pédagogiques',
      'Relation familles',
      'Outils d’évaluation',
      'Passerelle catégorie suivante',
      'Annexes pratiques',
    ],
    minimumTargets: { tables: 6, situations: 6, diagrams: 6, bcvbBlocks: 24 },
    qualityRules: [
      'Le document doit être lisible en profondeur.',
      'La posture du coach doit être explicite.',
      'Les relations familles doivent être cadrées.',
      'Les situations doivent rester exploitables terrain.',
    ],
  },
  plan_formation: {
    label: 'Plan de formation',
    purpose: 'Document institutionnel de pilotage technique et sportif.',
    format: 'A4 portrait',
    layout: 'Rapport institutionnel premium avec pages de transition pleine couleur.',
    visualSignature: 'Timeline, matrices, tableaux de bord, pyramide de formation, indicateurs.',
    requiredSections: [
      'Éditorial président / DTR',
      'Vision club',
      'Philosophie BCVB',
      'Parcours joueur',
      'Objectifs par catégorie',
      'Compétences par âge',
      'Méthode pédagogique',
      'Organisation technique',
      'Formation coachs',
      'Indicateurs de suivi',
      'Calendrier de mise en œuvre',
      'Tableaux de bord',
    ],
    minimumTargets: { tables: 10, situations: 0, diagrams: 4, bcvbBlocks: 26 },
    qualityRules: [
      'Le ton doit être institutionnel.',
      'La progression doit être pluriannuelle.',
      'Les indicateurs doivent être pilotables.',
      'Le rendu doit ressembler à un rapport professionnel.',
    ],
  },
  ruban_pedagogique: {
    label: 'Ruban pédagogique',
    purpose: 'Document synthétique de progression dans le temps.',
    format: 'A4 paysage',
    layout: 'Lecture horizontale par séances et verticale par thèmes.',
    visualSignature: 'Tableaux compacts, codes couleurs, progression claire.',
    requiredSections: [
      'Objectif général',
      'Public cible',
      'Cycle',
      'Progression par séances',
      'Objectifs par séance',
      'Situations supports',
      'Critères observables',
      'Régulations',
    ],
    minimumTargets: { tables: 4, situations: 0, diagrams: 0, bcvbBlocks: 12 },
    qualityRules: [
      'Le format paysage est obligatoire.',
      'La lecture doit être rapide.',
      'Chaque séance doit avoir un objectif clair.',
      'La progression doit être visible.',
    ],
  },
  seance_entrainement: {
    label: 'Séance d’entraînement',
    purpose: 'Document opérationnel utilisable directement dans le gymnase.',
    format: 'A4 portrait ou paysage selon besoin',
    layout: '1 page prioritaire, terrain visible, timing clair.',
    visualSignature: 'Lecture en 30 secondes, blocs courts, schéma immédiatement visible.',
    requiredSections: [
      'Objectif prioritaire',
      'Public',
      'Durée',
      'Matériel',
      'Timing',
      'Situation principale',
      'Schéma terrain',
      'Consignes',
      'Rotations',
      'Critères de réussite',
      'Vigilances coach',
      'Régulations',
    ],
    minimumTargets: { tables: 2, situations: 1, diagrams: 1, bcvbBlocks: 8 },
    qualityRules: [
      'Le document doit être utilisable avec les mains dans les filets.',
      'Le terrain doit être visible sans chercher.',
      'Le timing doit être clair.',
      'Les consignes doivent être courtes.',
    ],
  },
  fiche_theme: {
    label: 'Fiche à thème',
    purpose: 'Document ciblé sur un thème technique, tactique, physique ou mental.',
    format: 'A4 portrait',
    layout: 'Structure flexible avec bannière colorée selon le thème.',
    visualSignature: 'Reconnaissance rapide dans une liasse de fiches.',
    requiredSections: [
      'Thème',
      'Public cible',
      'Objectif',
      'Repères clés',
      'Erreurs fréquentes',
      'Points coach',
      'Situations pédagogiques',
      'Variantes',
      'Transfert match',
      'Synthèse',
    ],
    minimumTargets: { tables: 3, situations: 3, diagrams: 3, bcvbBlocks: 12 },
    qualityRules: [
      'Le document doit être ciblé.',
      'Le thème doit être identifiable immédiatement.',
      'Les situations doivent être concrètes.',
      'Les erreurs fréquentes doivent être utiles au coach.',
    ],
  },
} as const

export function getEditorialStandard(family: DocumentFamily) {
  return EDITORIAL_STANDARDS[family]
}
