import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { formatUserFacingError } from '../../lib/userFacingError'
import { buildTechnicalDashboardModel } from './technicalDashboardCalculations'
import { fetchTechnicalDashboard } from './technicalDashboardService'
import type { TechnicalDashboardModel, TechnicalDashboardRole } from './types'
import './TechnicalDashboard.css'

export default function TechnicalDashboard({ role }: { role: TechnicalDashboardRole }) {
  const [model, setModel] = useState<TechnicalDashboardModel | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [category, setCategory] = useState('all')
  const canReadDetails = role !== 'dirigeant'
  async function load() { try { setLoading(true); setError(null); setModel(buildTechnicalDashboardModel(await fetchTechnicalDashboard(role))) } catch (cause) { setError(formatUserFacingError(cause, 'Le tableau de bord technique ne peut pas être chargé pour le moment.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [role])
  const visibleTeams = useMemo(() => model?.teams.filter((team) => category === 'all' || team.category === category) || [], [category, model])
  if (loading) return <section className="technical-dashboard-state" aria-live="polite"><h2>Chargement de la situation du club…</h2><p>Équipes, encadrement et alertes sont en cours de lecture.</p></section>
  if (error) return <section className="technical-dashboard-state technical-dashboard-state--error"><h2>Données indisponibles</h2><p>{error}</p><button type="button" onClick={() => void load()}>Réessayer</button></section>
  if (!model) return null
  return <div className="technical-dashboard">
    <header className="technical-dashboard__hero"><div><p className="bcvb-eyebrow">Pilotage sportif BCVB</p><h1>Tableau de bord technique</h1><p>Les équipes à sécuriser et les actions prioritaires, à partir des données partagées du club.</p></div><Link className="technical-dashboard__primary" to="/club/equipes">Ouvrir les équipes</Link></header>
    <section className="technical-dashboard__block technical-dashboard__alerts"><div className="technical-dashboard__block-header"><div><p className="bcvb-eyebrow">À traiter</p><h2>Priorités du club</h2></div>{model.alerts.length ? <span>{model.alerts.length} priorité{model.alerts.length > 1 ? 's' : ''}</span> : null}</div>{model.alerts.length === 0 ? <p className="technical-dashboard__empty">Aucune alerte calculable avec les données accessibles.</p> : <div className="technical-dashboard__alert-list">{model.alerts.map((alert) => <article key={alert.id}><div><strong>{alert.count}</strong><span>{alert.label}</span></div>{alert.path ? <Link to={alert.path}>Traiter</Link> : null}</article>)}</div>}</section>
    <section className="technical-dashboard__block"><div className="technical-dashboard__block-header"><div><p className="bcvb-eyebrow">Aujourd’hui / prochainement</p><h2>Planning des équipes</h2></div><Link to="/planning">Ouvrir le planning</Link></div>{model.schedule.length===0?<div className="technical-dashboard__empty"><strong>Aucun créneau partagé actif</strong><p>Créez les créneaux opérationnels pour alimenter cette vue.</p></div>:<div className="technical-dashboard__team-list">{model.schedule.slice(0,6).map(slot=><article key={slot.id}><h3>{slot.isToday?'Aujourd’hui · ':''}{slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)} · {slot.teamName}</h3><p>{slot.location_name||'Salle non renseignée'}{slot.hasConflict?' · Chevauchement de salle détecté':''}</p><Link to={`/club/equipes/${slot.team_id}`}>Ouvrir l’équipe</Link></article>)}</div>}<p className="technical-dashboard__muted">Information de pilotage · Équipes sans créneau actif : {model.teamsWithoutActiveSlot}</p></section>
    <section className="technical-dashboard__block"><div className="technical-dashboard__block-header"><div><p className="bcvb-eyebrow">Équipes</p><h2>Couverture des équipes</h2></div><label><span>Catégorie</span><select aria-label="Filtrer par catégorie" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Toutes</option>{model.categories.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="technical-dashboard__metrics"><article><span>Équipes actives</span><strong>{model.teamCount}</strong><p>Groupes non archivés.</p></article><article className={model.teamsWithoutHeadCoach ? 'is-alert' : ''}><span>Sans coach principal</span><strong>{model.teamsWithoutHeadCoach}</strong><p>À couvrir en priorité.</p></article><article><span>Avec coach principal</span><strong>{model.teamCount - model.teamsWithoutHeadCoach}</strong><p>Coach enregistré ou affecté.</p></article></div>{visibleTeams.length === 0 ? <p className="technical-dashboard__empty">Aucune équipe ne correspond à ce filtre.</p> : <div className="technical-dashboard__team-list">{visibleTeams.map((team) => <article key={team.id}><div className="technical-dashboard__team-top"><div><span>{team.category || 'Catégorie non renseignée'}</span><h3>{team.name || 'Équipe sans nom'}</h3><p>{[team.level, team.season].filter(Boolean).join(' · ') || 'Niveau et saison non renseignés'}</p></div><span className={team.hasHeadCoach ? 'is-ok' : 'is-missing'}>{team.hasHeadCoach ? 'Coach principal couvert' : 'Coach principal manquant'}</span></div><Link to={`/club/equipes/${team.id}`}>Ouvrir la fiche équipe</Link></article>)}</div>}</section>
    <section className="technical-dashboard__block"><div className="technical-dashboard__block-header"><div><p className="bcvb-eyebrow">Encadrement</p><h2>Affectations enregistrées</h2></div><Link to="/club/equipes">Gérer les équipes</Link></div><div className="technical-dashboard__metrics"><article><span>Coachs affectés</span><strong>{model.assignedCoachCount ?? '—'}</strong><p>Personnes uniques enregistrées.</p></article><article><span>Parents référents</span><strong>{model.parentReferentCount ?? '—'}</strong><p>Affectations actives.</p></article></div>{canReadDetails ? <div className="technical-dashboard__staff-list">{model.teams.map((team) => <article key={team.id}><h3>{team.name}</h3>{team.staffMembers?.length ? <ul>{team.staffMembers.map((member) => <li key={`${team.id}-${member.id}`}><strong>{member.name}</strong><span>{member.role}</span></li>)}</ul> : <p>Aucune personne affectée.</p>}<p className="technical-dashboard__muted">Coach adjoint : {team.hasAssistantCoach ? 'renseigné' : 'non renseigné'} · Parent référent : {team.hasParentReferent ? 'renseigné' : 'non renseigné'}</p></article>)}</div> : <p className="technical-dashboard__empty">Les affectations nominatives sont réservées à la direction technique et à l’administration.</p>}</section>
    <section className="technical-dashboard__block"><div className="technical-dashboard__block-header"><div><p className="bcvb-eyebrow">Actions rapides</p><h2>Accès directs</h2></div></div><nav className="technical-dashboard__actions" aria-label="Actions techniques"><Link to="/club/equipes">Équipes</Link><Link to="/planning">Planning</Link><Link to="/presences">Présences</Link><Link to="/generateur">Créer une séance</Link>{canReadDetails ? <><Link to="/admin/inscriptions">Inscriptions</Link><Link to="/admin/demandes-profils">Demandes de profils</Link></> : null}</nav><p className="technical-dashboard__source-note">Les présences sont accessibles, mais ne disposent pas encore d’une source partagée exploitable pour une synthèse club.</p></section>
  </div>
}
