import type { DocumentFamily, ExportConfig } from "../../types/admin";

export const defaultExportSettings: ExportConfig[] = [
  {
    family: "cahier_technique",
    format: "a4_portrait",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: true,
    includeSourceMarkdown: true,
    marginTopMm: 16,
    marginRightMm: 14,
    marginBottomMm: 16,
    marginLeftMm: 14,
  },
  {
    family: "guide_coach",
    format: "a4_portrait",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: true,
    includeSourceMarkdown: true,
    marginTopMm: 14,
    marginRightMm: 14,
    marginBottomMm: 14,
    marginLeftMm: 14,
  },
  {
    family: "plan_formation",
    format: "a4_landscape",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: true,
    includeSourceMarkdown: true,
    marginTopMm: 12,
    marginRightMm: 12,
    marginBottomMm: 12,
    marginLeftMm: 12,
  },
  {
    family: "ruban_pedagogique",
    format: "a4_landscape",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: true,
    includeSourceMarkdown: false,
    marginTopMm: 10,
    marginRightMm: 10,
    marginBottomMm: 10,
    marginLeftMm: 10,
  },
  {
    family: "seance_entrainement",
    format: "a4_portrait",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: false,
    includeSourceMarkdown: false,
    marginTopMm: 10,
    marginRightMm: 10,
    marginBottomMm: 10,
    marginLeftMm: 10,
  },
  {
    family: "fiche_theme",
    format: "a4_portrait",
    includeLogo: true,
    includeFooter: true,
    includePageNumbers: true,
    includeSourceMarkdown: true,
    marginTopMm: 12,
    marginRightMm: 12,
    marginBottomMm: 12,
    marginLeftMm: 12,
  },
];

export function findExportConfig(exports: ExportConfig[], family: DocumentFamily) {
  return exports.find((config) => config.family === family);
}
